name: HistoryManager
author:  arieh
current:  0.4.1
category: Utilities 
tags:  [AJAX,Interface,Observer]
demo: http://arieh.github.com/HistoryManager/
docs: http://moodocs.net/arieh/historymanager/HistoryManager
